name: "Login to Docker"
description: "Setup Buildx and Login to Docker Hub"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true

runs:
  using: "composite"
  steps:
      - uses: docker/login-action@v3
        with:
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}
      - uses: docker/setup-buildx-action@v3
